[package]
name = "bolt-codegen"
version = "0.1.0"
edition = "2024"

[dependencies]
inkwell.workspace = true
anyhow.workspace = true
thiserror.workspace = true
bolt-ast = { path = "../bolt-ast" }
bolt-types = { path = "../bolt-types" }
