[package]
name = "bolt-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
nom.workspace = true
thiserror.workspace = true
bolt-lexer = { path = "../bolt-lexer" }
bolt-ast = { path = "../bolt-ast" }
